language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  skip_cleanup: true
  keep_history: true
  local_dir: dist
